pipeline {
    agent any

    stages {
        stage('Pull Code From GitHub') {
            steps {
                git 'https://github.com/Rajeshraahul/Kubernetes_project.git'
            }
        }
        stage('Build the Docker image') {
            steps {
                sh 'sudo docker build -t devopskuber /var/lib/jenkins/workspace/project/Github'
                sh 'sudo docker tag devopskuber rajeshraahul/devopskuber:latest'
                sh 'sudo docker tag devopskuber rajeshraahul/devopskuber:${BUILD_NUMBER}'
            }
        }
        stage('Push the Docker image') {
            steps {
                sh 'sudo docker image push rajeshraahul/devopskuber:latest'
                sh 'sudo docker image push rajeshraahul/devopskuber:${BUILD_NUMBER}'
            }
        }
        stage('Deploy on Kubernetes') {
        steps {
            sh 'sudo kubectl apply -f /var/lib/jenkins/workspace/project/Github/pod.yaml --validate=false'
            sh 'sudo kubectl rollout restart deployment loadbalancer-pod'
        }
    }
    }
}